source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
gem "just-the-docs"

gem "kramdown", ">= 2.3.1"
gem "nokogiri", ">= 1.12.5"
gem "commonmarker", ">= 0.23.4"

gem 'activesupport', '~> 6.1'

gem "webrick", "~> 1.8"
